# Ruff configuration file

# Same as pyproject.toml settings but in dedicated file
line-length = 100
target-version = "py310"

# Exclude common directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), isort (`I`), naming (`N`), and pyupgrade (`UP`)
select = ["E", "F", "I", "N", "W", "UP"]

# Never enforce line length violations
ignore = ["E501"]

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Use Unix line endings
line-ending = "auto"

[lint.isort]
known-first-party = ["hl_api"]

[lint.pydocstyle]
convention = "google"